# Generated by Django 3.1.7 on 2021-03-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210331_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='user',
            new_name='employee',
        ),
    ]
